
language: cpp

compiler:
    - gcc

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc make cmake build-essential cpp libevent-dev libssl-dev
    - sudo apt-get install -qq libboost-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev libboost-thread-dev libboost-serialization-dev libboost-system-dev libmysqlclient-dev python-dev unixodbc unixodbc-dev

before_script:
    - cd  thirdparty/   
    - sh thirdparty-build.sh 
    - cd ..
    - mkdir build     
    - cd build
    - cmake ..

script:
    - make
    - ctest

