site_name: Android SDK

pages:
  - [index.md, Main] 
  - [tutorial.md, Tutorial]
  - [advanced-topics.md, Advanced Topics]
  - [faq.md, FAQ]
  - [changlog.md, Change Logs]
  
theme_dir : './srch2-theme'

